### ISSUE TITLE
Found broken `/graphql/apollo-angular/get-started` link. Please fix!

### ISSUE THREAD

**Issue by gandradeglez** [the-guild-org/the-guild-website#902] opened 2022-11-04 16:56 UTC
![image](https://user-images.githubusercontent.com/55098163/200032372-c77d2258-d8c1-4edf-a4fd-235fb2af32fe.png)

**Comment by dotansimha** [comment] 2022-11-05 10:03
dupe of https://github.com/the-guild-org/the-guild-website/issues/871

**Closed by dotansimha** 2022-11-05 10:03 UTC

**Comment by TuvalSimha** [comment] 2022-11-06 11:18
Hi @gandradeglez ,
Thank you for the bug report, it helps us a lot!

We did some fixed and now it should work, you can find the changes we did here: https://github.com/kamilkisiela/apollo-angular/pull/1837

You are more than welcome to try again:
https://the-guild.dev/graphql/apollo-angular/get-started
